language: java
env:
  global:
   - BUILD_DATE=$(date -u)
jdk:
 - openjdk8

sudo: required

install: false

services:
  - docker                  

before_install:            
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - travis_wait 30 $TRAVIS_BUILD_DIR/validate.sh
  - docker run -v $TRAVIS_BUILD_DIR/specification_document-developments/2_0-Metabolomics-Draft/:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -d book -a commit-hash=$TRAVIS_COMMIT -a build-date=$BUILD_DATE -D /documents/output mzTab_format_specification_2_0-M_draft.adoc      
  - docker run -v $TRAVIS_BUILD_DIR/specification_document-developments/2_0-Metabolomics-Draft/:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -d book -a commit-hash=$TRAVIS_COMMIT -a build-date=$BUILD_DATE -D /documents/output mzTab_format_specification_2_0-M_draft.adoc    

after_error: 
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_success:      
  - mkdir output/2_0-metabolomics-draft
  - cp -R $TRAVIS_BUILD_DIR/specification_document-developments/2_0-Metabolomics-Draft/output/* output/2_0-metabolomics-draft
  - mkdir output/2_0-metabolomics-draft/img
  - cp -R $TRAVIS_BUILD_DIR/specification_document-developments/2_0-Metabolomics-Draft/img/* output/2_0-metabolomics-draft/img
  - cp -R $TRAVIS_BUILD_DIR/docs/* output/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  keep-history: true
  on:
    branch: master

