language: java
env:
  global:
   - BUILD_DATE=$(date -u)
   - MZTAB-M_IN=$TRAVIS_BUILD_DIR/specification_document-developments/2_0-Metabolomics-Draft
   - MZTAB-M_OUT=$MZTAB-M_IN/output
   - MZTAB-M_DOC=mzTab_format_specification_2_0-M_draft.adoc  
jdk:
 - openjdk8

sudo: required

install: false

services:
  - docker                  

before_install:            
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - travis_wait 30 $TRAVIS_BUILD_DIR/validate.sh
  - $TRAVIS_BUILD_DIR/build-docs.sh -i $MZTAB-M_IN -o $MZTAB-M_OUT -c $TRAVIS_COMMIT -d $BUILD_DATE -f $MZTAB-M_DOC

after_error: 
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf
  - docker logs asciidoc-to-docbook

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf
  - docker logs asciidoc-to-docbook

after_success:      
  - mkdir output/2_0-metabolomics-draft
  - cp -R $TRAVIS_BUILD_DIR/specification_document-developments/2_0-Metabolomics-Draft/output/* output/2_0-metabolomics-draft
  - mkdir output/2_0-metabolomics-draft/img
  - cp -R $TRAVIS_BUILD_DIR/specification_document-developments/2_0-Metabolomics-Draft/img/* output/2_0-metabolomics-draft/img
  - cp -R $TRAVIS_BUILD_DIR/docs/* output/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  keep-history: true
  on:
    branch: master

